def override_dependency():
    return [
        {
            "key_as_string": "2020-03-02T00:00:00.000Z",
            "key": 1583107200000,
            "doc_count": 1,
            "jumlah_meninggal": {"value": 1},
            "jumlah_sembuh": {"value": 1},
            "jumlah_positif": {"value": 2},
            "jumlah_dirawat": {"value": 2},
            "jumlah_positif_kum": {"value": 2},
            "jumlah_sembuh_kum": {"value": 0},
            "jumlah_meninggal_kum": {"value": 0},
            "jumlah_dirawat_kum": {"value": 2},
        },
        {
            "key_as_string": "2020-03-03T00:00:00.000Z",
            "key": 1583193600000,
            "doc_count": 1,
            "jumlah_meninggal": {"value": 3},
            "jumlah_sembuh": {"value": 3},
            "jumlah_positif": {"value": 4},
            "jumlah_dirawat": {"value": 4},
            "jumlah_positif_kum": {"value": 2},
            "jumlah_sembuh_kum": {"value": 0},
            "jumlah_meninggal_kum": {"value": 0},
            "jumlah_dirawat_kum": {"value": 2},
        },
        {
            "key_as_string": "2021-01-01T00:00:00.000Z",
            "key": 1609459200000,
            "doc_count": 1,
            "jumlah_meninggal": {"value": 1},
            "jumlah_sembuh": {"value": 1},
            "jumlah_positif": {"value": 2},
            "jumlah_dirawat": {"value": 2},
            "jumlah_positif_kum": {"value": 3},
            "jumlah_sembuh_kum": {"value": 0},
            "jumlah_meninggal_kum": {"value": 5},
            "jumlah_dirawat_kum": {"value": 1},
        },
        {
            "key_as_string": "2021-01-02T00:00:00.000Z",
            "key": 1609545600000,
            "doc_count": 1,
            "jumlah_meninggal": {"value": 3},
            "jumlah_sembuh": {"value": 3},
            "jumlah_positif": {"value": 4},
            "jumlah_dirawat": {"value": 4},
            "jumlah_positif_kum": {"value": 2},
            "jumlah_sembuh_kum": {"value": 0},
            "jumlah_meninggal_kum": {"value": 0},
            "jumlah_dirawat_kum": {"value": 1},
        },
        {
            "key_as_string": "2022-01-02T00:00:00.000Z",
            "key": 1641081600000,
            "doc_count": 1,
            "jumlah_meninggal": {"value": 5},
            "jumlah_sembuh": {"value": 5},
            "jumlah_positif": {"value": 6},
            "jumlah_dirawat": {"value": 6},
            "jumlah_positif_kum": {"value": 4},
            "jumlah_sembuh_kum": {"value": 1},
            "jumlah_meninggal_kum": {"value": 0},
            "jumlah_dirawat_kum": {"value": 0},
        },
    ]
